/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProposalManagerLazyImport = createFileRoute('/proposal-manager')()

// Create/Update Routes

const ProposalManagerLazyRoute = ProposalManagerLazyImport.update({
  id: '/proposal-manager',
  path: '/proposal-manager',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/proposal-manager.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proposal-manager': {
      id: '/proposal-manager'
      path: '/proposal-manager'
      fullPath: '/proposal-manager'
      preLoaderRoute: typeof ProposalManagerLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/proposal-manager': typeof ProposalManagerLazyRoute
}

export interface FileRoutesByTo {
  '/proposal-manager': typeof ProposalManagerLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/proposal-manager': typeof ProposalManagerLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/proposal-manager'
  fileRoutesByTo: FileRoutesByTo
  to: '/proposal-manager'
  id: '__root__' | '/proposal-manager'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProposalManagerLazyRoute: typeof ProposalManagerLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  ProposalManagerLazyRoute: ProposalManagerLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/proposal-manager"
      ]
    },
    "/proposal-manager": {
      "filePath": "proposal-manager.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
